from collections.abc import Iterator
import enum
from typing import Any, Callable, ClassVar, Literal

from . import enums
from . import lzc
from . import property_sets

__all__ = ["enums", "lzc", "property_sets"]

class struct_vdev_stats:
    allocated: int
    space: int
    dspace: int
    pspace: int
    rsize: int
    esize: int
    read_errors: int
    write_errors: int
    checksum_errors: int
    initialize_errors: int
    dio_verify_errors: int
    slow_ios: int | None
    self_healed_bytes: int

class struct_vdev:
    name: str
    vdev_type: str
    guid: int
    state: enums.VDevState
    stats: struct_vdev_stats | None
    children: tuple[struct_vdev, ...] | None
    top_guid: int | None

class struct_support_vdev:
    cache: tuple[struct_vdev, ...]
    log: tuple[struct_vdev, ...]
    special: tuple[struct_vdev, ...]
    dedup: tuple[struct_vdev, ...]

class struct_zpool_feature:
    guid: str
    description: str
    state: Literal["DISABLED", "ENABLED", "ACTIVE"]

class struct_zpool_status:
    status: ZPOOLStatus
    reason: str | None
    action: str | None
    message: str | None
    corrupted_files: tuple[str, ...]
    storage_vdevs: tuple[struct_vdev, ...]
    support_vdevs: struct_support_vdev
    spares: tuple[struct_vdev, ...]

class PropertySource(enum.IntFlag):
    __new__: ClassVar[Callable] = ...
    DEFAULT: ClassVar[PropertySource] = ...
    INHERITED: ClassVar[PropertySource] = ...
    LOCAL: ClassVar[PropertySource] = ...
    NONE: ClassVar[PropertySource] = ...
    RECEIVED: ClassVar[PropertySource] = ...
    TEMPORARY: ClassVar[PropertySource] = ...
    _all_bits_: ClassVar[int] = ...
    _boundary_: ClassVar[enum.FlagBoundary] = ...
    _flag_mask_: ClassVar[int] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _inverted_: ClassVar[None] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _singles_mask_: ClassVar[int] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    __and__: ClassVar[Callable] = ...
    __invert__: ClassVar[Callable] = ...
    __or__: ClassVar[Callable] = ...
    __rand__: ClassVar[Callable] = ...
    __ror__: ClassVar[Callable] = ...
    __rxor__: ClassVar[Callable] = ...
    __xor__: ClassVar[Callable] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class VDevAuxState(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    VDEV_AUX_ACTIVE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_ASHIFT_TOO_BIG: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_ASHIFT: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_GUID_SUM: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_LABEL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_LOG: ClassVar[VDevAuxState] = ...
    VDEV_AUX_CHILDREN_OFFLINE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_CORRUPT_DATA: ClassVar[VDevAuxState] = ...
    VDEV_AUX_ERR_EXCEEDED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_EXTERNAL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_EXTERNAL_PERSIST: ClassVar[VDevAuxState] = ...
    VDEV_AUX_IO_FAILURE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_NONE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_NO_REPLICAS: ClassVar[VDevAuxState] = ...
    VDEV_AUX_OPEN_FAILED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_SPARED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_SPLIT_POOL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_TOO_SMALL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_UNSUP_FEAT: ClassVar[VDevAuxState] = ...
    VDEV_AUX_VERSION_NEWER: ClassVar[VDevAuxState] = ...
    VDEV_AUX_VERSION_OLDER: ClassVar[VDevAuxState] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSDOSFlag(enum.IntFlag):
    __new__: ClassVar[Callable] = ...
    ZFS_APPENDONLY: ClassVar[ZFSDOSFlag] = ...
    ZFS_ARCHIVE: ClassVar[ZFSDOSFlag] = ...
    ZFS_HIDDEN: ClassVar[ZFSDOSFlag] = ...
    ZFS_IMMUTABLE: ClassVar[ZFSDOSFlag] = ...
    ZFS_NODUMP: ClassVar[ZFSDOSFlag] = ...
    ZFS_NOUNLINK: ClassVar[ZFSDOSFlag] = ...
    ZFS_READONLY: ClassVar[ZFSDOSFlag] = ...
    ZFS_SPARSE: ClassVar[ZFSDOSFlag] = ...
    ZFS_SYSTEM: ClassVar[ZFSDOSFlag] = ...
    _all_bits_: ClassVar[int] = ...
    _boundary_: ClassVar[enum.FlagBoundary] = ...
    _flag_mask_: ClassVar[int] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _inverted_: ClassVar[None] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _singles_mask_: ClassVar[int] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    __and__: ClassVar[Callable] = ...
    __invert__: ClassVar[Callable] = ...
    __or__: ClassVar[Callable] = ...
    __rand__: ClassVar[Callable] = ...
    __ror__: ClassVar[Callable] = ...
    __rxor__: ClassVar[Callable] = ...
    __xor__: ClassVar[Callable] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSError(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    EZFS_ACTIVE_POOL: ClassVar[ZFSError] = ...
    EZFS_ACTIVE_SPARE: ClassVar[ZFSError] = ...
    EZFS_ASHIFT_MISMATCH: ClassVar[ZFSError] = ...
    EZFS_BADBACKUP: ClassVar[ZFSError] = ...
    EZFS_BADCACHE: ClassVar[ZFSError] = ...
    EZFS_BADDEV: ClassVar[ZFSError] = ...
    EZFS_BADPATH: ClassVar[ZFSError] = ...
    EZFS_BADPERM: ClassVar[ZFSError] = ...
    EZFS_BADPERMSET: ClassVar[ZFSError] = ...
    EZFS_BADPROP: ClassVar[ZFSError] = ...
    EZFS_BADRESTORE: ClassVar[ZFSError] = ...
    EZFS_BADSTREAM: ClassVar[ZFSError] = ...
    EZFS_BADTARGET: ClassVar[ZFSError] = ...
    EZFS_BADTYPE: ClassVar[ZFSError] = ...
    EZFS_BADVERSION: ClassVar[ZFSError] = ...
    EZFS_BADWHO: ClassVar[ZFSError] = ...
    EZFS_BUSY: ClassVar[ZFSError] = ...
    EZFS_CHECKPOINT_EXISTS: ClassVar[ZFSError] = ...
    EZFS_CKSUM: ClassVar[ZFSError] = ...
    EZFS_CROSSTARGET: ClassVar[ZFSError] = ...
    EZFS_CRYPTOFAILED: ClassVar[ZFSError] = ...
    EZFS_DEVOVERFLOW: ClassVar[ZFSError] = ...
    EZFS_DEVRM_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_DIFF: ClassVar[ZFSError] = ...
    EZFS_DIFFDATA: ClassVar[ZFSError] = ...
    EZFS_DISCARDING_CHECKPOINT: ClassVar[ZFSError] = ...
    EZFS_DSREADONLY: ClassVar[ZFSError] = ...
    EZFS_ERRORSCRUBBING: ClassVar[ZFSError] = ...
    EZFS_ERRORSCRUB_PAUSED: ClassVar[ZFSError] = ...
    EZFS_EXISTS: ClassVar[ZFSError] = ...
    EZFS_EXPORT_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_FAULT: ClassVar[ZFSError] = ...
    EZFS_INITIALIZING: ClassVar[ZFSError] = ...
    EZFS_INTR: ClassVar[ZFSError] = ...
    EZFS_INVALCONFIG: ClassVar[ZFSError] = ...
    EZFS_INVALIDNAME: ClassVar[ZFSError] = ...
    EZFS_IO: ClassVar[ZFSError] = ...
    EZFS_IOC_NOTSUPPORTED: ClassVar[ZFSError] = ...
    EZFS_ISL2CACHE: ClassVar[ZFSError] = ...
    EZFS_ISSPARE: ClassVar[ZFSError] = ...
    EZFS_LABELFAILED: ClassVar[ZFSError] = ...
    EZFS_MOUNTFAILED: ClassVar[ZFSError] = ...
    EZFS_NAMETOOLONG: ClassVar[ZFSError] = ...
    EZFS_NOCAP: ClassVar[ZFSError] = ...
    EZFS_NODELEGATION: ClassVar[ZFSError] = ...
    EZFS_NODEVICE: ClassVar[ZFSError] = ...
    EZFS_NOENT: ClassVar[ZFSError] = ...
    EZFS_NOHISTORY: ClassVar[ZFSError] = ...
    EZFS_NOMEM: ClassVar[ZFSError] = ...
    EZFS_NOREPLICAS: ClassVar[ZFSError] = ...
    EZFS_NOSPC: ClassVar[ZFSError] = ...
    EZFS_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_NOT_USER_NAMESPACE: ClassVar[ZFSError] = ...
    EZFS_NO_CHECKPOINT: ClassVar[ZFSError] = ...
    EZFS_NO_INITIALIZE: ClassVar[ZFSError] = ...
    EZFS_NO_PENDING: ClassVar[ZFSError] = ...
    EZFS_NO_RESILVER_DEFER: ClassVar[ZFSError] = ...
    EZFS_NO_SCRUB: ClassVar[ZFSError] = ...
    EZFS_NO_TRIM: ClassVar[ZFSError] = ...
    EZFS_OPENFAILED: ClassVar[ZFSError] = ...
    EZFS_PERM: ClassVar[ZFSError] = ...
    EZFS_PIPEFAILED: ClassVar[ZFSError] = ...
    EZFS_POOLPROPS: ClassVar[ZFSError] = ...
    EZFS_POOLREADONLY: ClassVar[ZFSError] = ...
    EZFS_POOLUNAVAIL: ClassVar[ZFSError] = ...
    EZFS_POOL_INVALARG: ClassVar[ZFSError] = ...
    EZFS_POOL_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_POSTSPLIT_ONLINE: ClassVar[ZFSError] = ...
    EZFS_PROPNONINHERIT: ClassVar[ZFSError] = ...
    EZFS_PROPREADONLY: ClassVar[ZFSError] = ...
    EZFS_PROPSPACE: ClassVar[ZFSError] = ...
    EZFS_PROPTYPE: ClassVar[ZFSError] = ...
    EZFS_RAIDZ_EXPAND_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_REBUILDING: ClassVar[ZFSError] = ...
    EZFS_RECURSIVE: ClassVar[ZFSError] = ...
    EZFS_REFTAG_HOLD: ClassVar[ZFSError] = ...
    EZFS_REFTAG_RELE: ClassVar[ZFSError] = ...
    EZFS_RESILVERING: ClassVar[ZFSError] = ...
    EZFS_RESUME_EXISTS: ClassVar[ZFSError] = ...
    EZFS_SCRUBBING: ClassVar[ZFSError] = ...
    EZFS_SCRUB_PAUSED: ClassVar[ZFSError] = ...
    EZFS_SCRUB_PAUSED_TO_CANCEL: ClassVar[ZFSError] = ...
    EZFS_SHAREFAILED: ClassVar[ZFSError] = ...
    EZFS_SHARENFSFAILED: ClassVar[ZFSError] = ...
    EZFS_SHARESMBFAILED: ClassVar[ZFSError] = ...
    EZFS_SUCCESS: ClassVar[ZFSError] = ...
    EZFS_TAGTOOLONG: ClassVar[ZFSError] = ...
    EZFS_THREADCREATEFAILED: ClassVar[ZFSError] = ...
    EZFS_TOOMANY: ClassVar[ZFSError] = ...
    EZFS_TRIMMING: ClassVar[ZFSError] = ...
    EZFS_TRIM_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_UMOUNTFAILED: ClassVar[ZFSError] = ...
    EZFS_UNKNOWN: ClassVar[ZFSError] = ...
    EZFS_UNPLAYED_LOGS: ClassVar[ZFSError] = ...
    EZFS_UNSHARENFSFAILED: ClassVar[ZFSError] = ...
    EZFS_UNSHARESMBFAILED: ClassVar[ZFSError] = ...
    EZFS_VDEVNOTSUP: ClassVar[ZFSError] = ...
    EZFS_VDEV_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_VDEV_TOO_BIG: ClassVar[ZFSError] = ...
    EZFS_VOLTOOBIG: ClassVar[ZFSError] = ...
    EZFS_WRONG_PARENT: ClassVar[ZFSError] = ...
    EZFS_ZONED: ClassVar[ZFSError] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSException(RuntimeError):
    action: ClassVar[str] = ...
    code: ClassVar[int] = ...
    description: ClassVar[str] = ...
    err_str: ClassVar[str] = ...
    location: ClassVar[str] = ...
    name: ClassVar[str] = ...

class ZFSProperty(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ACLINHERIT: ClassVar[ZFSProperty] = ...
    ACLMODE: ClassVar[ZFSProperty] = ...
    ACLTYPE: ClassVar[ZFSProperty] = ...
    ATIME: ClassVar[ZFSProperty] = ...
    AVAILABLE: ClassVar[ZFSProperty] = ...
    CANMOUNT: ClassVar[ZFSProperty] = ...
    CASESENSITIVITY: ClassVar[ZFSProperty] = ...
    CHECKSUM: ClassVar[ZFSProperty] = ...
    CLONES: ClassVar[ZFSProperty] = ...
    COMPRESSION: ClassVar[ZFSProperty] = ...
    COMPRESSRATIO: ClassVar[ZFSProperty] = ...
    CONTEXT: ClassVar[ZFSProperty] = ...
    COPIES: ClassVar[ZFSProperty] = ...
    CREATETXG: ClassVar[ZFSProperty] = ...
    CREATION: ClassVar[ZFSProperty] = ...
    DEDUP: ClassVar[ZFSProperty] = ...
    DEFAULTGROUPOBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTGROUPQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTPROJECTOBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTPROJECTQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTUSEROBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTUSERQUOTA: ClassVar[ZFSProperty] = ...
    DEFCONTEXT: ClassVar[ZFSProperty] = ...
    DEFER_DESTROY: ClassVar[ZFSProperty] = ...
    DEVICES: ClassVar[ZFSProperty] = ...
    DIRECT: ClassVar[ZFSProperty] = ...
    DNODESIZE: ClassVar[ZFSProperty] = ...
    ENCRYPTION: ClassVar[ZFSProperty] = ...
    ENCRYPTIONROOT: ClassVar[ZFSProperty] = ...
    EXEC: ClassVar[ZFSProperty] = ...
    FILESYSTEM_COUNT: ClassVar[ZFSProperty] = ...
    FILESYSTEM_LIMIT: ClassVar[ZFSProperty] = ...
    FSCONTEXT: ClassVar[ZFSProperty] = ...
    GUID: ClassVar[ZFSProperty] = ...
    KEYFORMAT: ClassVar[ZFSProperty] = ...
    KEYLOCATION: ClassVar[ZFSProperty] = ...
    KEYSTATUS: ClassVar[ZFSProperty] = ...
    LOGBIAS: ClassVar[ZFSProperty] = ...
    LOGICALREFERENCED: ClassVar[ZFSProperty] = ...
    LOGICALUSED: ClassVar[ZFSProperty] = ...
    LONGNAME: ClassVar[ZFSProperty] = ...
    MLSLABEL: ClassVar[ZFSProperty] = ...
    MOUNTED: ClassVar[ZFSProperty] = ...
    MOUNTPOINT: ClassVar[ZFSProperty] = ...
    NBMAND: ClassVar[ZFSProperty] = ...
    NORMALIZATION: ClassVar[ZFSProperty] = ...
    OBJSETID: ClassVar[ZFSProperty] = ...
    ORIGIN: ClassVar[ZFSProperty] = ...
    OVERLAY: ClassVar[ZFSProperty] = ...
    PBKDF2ITERS: ClassVar[ZFSProperty] = ...
    PREFETCH: ClassVar[ZFSProperty] = ...
    PRIMARYCACHE: ClassVar[ZFSProperty] = ...
    QUOTA: ClassVar[ZFSProperty] = ...
    READONLY: ClassVar[ZFSProperty] = ...
    RECEIVE_RESUME_TOKEN: ClassVar[ZFSProperty] = ...
    RECORDSIZE: ClassVar[ZFSProperty] = ...
    REDACT_SNAPS: ClassVar[ZFSProperty] = ...
    REDUNDANT_METADATA: ClassVar[ZFSProperty] = ...
    REFCOMPRESSRATIO: ClassVar[ZFSProperty] = ...
    REFERENCED: ClassVar[ZFSProperty] = ...
    REFQUOTA: ClassVar[ZFSProperty] = ...
    REFRESERVATION: ClassVar[ZFSProperty] = ...
    RELATIME: ClassVar[ZFSProperty] = ...
    RESERVATION: ClassVar[ZFSProperty] = ...
    ROOTCONTEXT: ClassVar[ZFSProperty] = ...
    SECONDARYCACHE: ClassVar[ZFSProperty] = ...
    SETUID: ClassVar[ZFSProperty] = ...
    SHARENFS: ClassVar[ZFSProperty] = ...
    SHARESMB: ClassVar[ZFSProperty] = ...
    SNAPDEV: ClassVar[ZFSProperty] = ...
    SNAPDIR: ClassVar[ZFSProperty] = ...
    SNAPSHOTS_CHANGED: ClassVar[ZFSProperty] = ...
    SNAPSHOT_COUNT: ClassVar[ZFSProperty] = ...
    SNAPSHOT_LIMIT: ClassVar[ZFSProperty] = ...
    SPECIAL_SMALL_BLOCKS: ClassVar[ZFSProperty] = ...
    SYNC: ClassVar[ZFSProperty] = ...
    TYPE: ClassVar[ZFSProperty] = ...
    USED: ClassVar[ZFSProperty] = ...
    USEDBYCHILDREN: ClassVar[ZFSProperty] = ...
    USEDBYDATASET: ClassVar[ZFSProperty] = ...
    USEDBYREFRESERVATION: ClassVar[ZFSProperty] = ...
    USEDBYSNAPSHOTS: ClassVar[ZFSProperty] = ...
    USERREFS: ClassVar[ZFSProperty] = ...
    UTF8ONLY: ClassVar[ZFSProperty] = ...
    VERSION: ClassVar[ZFSProperty] = ...
    VOLBLOCKSIZE: ClassVar[ZFSProperty] = ...
    VOLMODE: ClassVar[ZFSProperty] = ...
    VOLSIZE: ClassVar[ZFSProperty] = ...
    VOLTHREADING: ClassVar[ZFSProperty] = ...
    VSCAN: ClassVar[ZFSProperty] = ...
    WRITTEN: ClassVar[ZFSProperty] = ...
    XATTR: ClassVar[ZFSProperty] = ...
    ZONED: ClassVar[ZFSProperty] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ZFS_TYPE_BOOKMARK: ClassVar[ZFSType] = ...
    ZFS_TYPE_FILESYSTEM: ClassVar[ZFSType] = ...
    ZFS_TYPE_INVALID: ClassVar[ZFSType] = ...
    ZFS_TYPE_POOL: ClassVar[ZFSType] = ...
    ZFS_TYPE_SNAPSHOT: ClassVar[ZFSType] = ...
    ZFS_TYPE_VDEV: ClassVar[ZFSType] = ...
    ZFS_TYPE_VOLUME: ClassVar[ZFSType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSUserQuota(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    GROUPOBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    GROUPOBJ_USED: ClassVar[ZFSUserQuota] = ...
    GROUP_QUOTA: ClassVar[ZFSUserQuota] = ...
    GROUP_USED: ClassVar[ZFSUserQuota] = ...
    PROJECTOBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    PROJECTOBJ_USED: ClassVar[ZFSUserQuota] = ...
    PROJECT_QUOTA: ClassVar[ZFSUserQuota] = ...
    PROJECT_USED: ClassVar[ZFSUserQuota] = ...
    USEROBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    USEROBJ_USED: ClassVar[ZFSUserQuota] = ...
    USER_QUOTA: ClassVar[ZFSUserQuota] = ...
    USER_USED: ClassVar[ZFSUserQuota] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZPOOLProperty(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ALLOCATED: ClassVar[ZPOOLProperty] = ...
    ALTROOT: ClassVar[ZPOOLProperty] = ...
    ASHIFT: ClassVar[ZPOOLProperty] = ...
    AUTOEXPAND: ClassVar[ZPOOLProperty] = ...
    AUTOREPLACE: ClassVar[ZPOOLProperty] = ...
    AUTOTRIM: ClassVar[ZPOOLProperty] = ...
    BCLONERATIO: ClassVar[ZPOOLProperty] = ...
    BCLONESAVED: ClassVar[ZPOOLProperty] = ...
    BCLONEUSED: ClassVar[ZPOOLProperty] = ...
    BOOTFS: ClassVar[ZPOOLProperty] = ...
    CACHEFILE: ClassVar[ZPOOLProperty] = ...
    CAPACITY: ClassVar[ZPOOLProperty] = ...
    CHECKPOINT: ClassVar[ZPOOLProperty] = ...
    COMMENT: ClassVar[ZPOOLProperty] = ...
    COMPATIBILITY: ClassVar[ZPOOLProperty] = ...
    DEDUPCACHED: ClassVar[ZPOOLProperty] = ...
    DEDUPDITTO: ClassVar[ZPOOLProperty] = ...
    DEDUPRATIO: ClassVar[ZPOOLProperty] = ...
    DEDUP_TABLE_QUOTA: ClassVar[ZPOOLProperty] = ...
    DEDUP_TABLE_SIZE: ClassVar[ZPOOLProperty] = ...
    DEDUPSAVED: ClassVar[ZPOOLProperty] = ...
    DEDUPUSED: ClassVar[ZPOOLProperty] = ...
    DELEGATION: ClassVar[ZPOOLProperty] = ...
    EXPANDSZ: ClassVar[ZPOOLProperty] = ...
    FAILUREMODE: ClassVar[ZPOOLProperty] = ...
    FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    FREE: ClassVar[ZPOOLProperty] = ...
    FREEING: ClassVar[ZPOOLProperty] = ...
    GUID: ClassVar[ZPOOLProperty] = ...
    HEALTH: ClassVar[ZPOOLProperty] = ...
    INVAL: ClassVar[ZPOOLProperty] = ...
    LAST_SCRUBBED_TXG: ClassVar[ZPOOLProperty] = ...
    LEAKED: ClassVar[ZPOOLProperty] = ...
    LISTSNAPS: ClassVar[ZPOOLProperty] = ...
    LOAD_GUID: ClassVar[ZPOOLProperty] = ...
    MAXBLOCKSIZE: ClassVar[ZPOOLProperty] = ...
    MAXDNODESIZE: ClassVar[ZPOOLProperty] = ...
    MULTIHOST: ClassVar[ZPOOLProperty] = ...
    NAME: ClassVar[ZPOOLProperty] = ...
    READONLY: ClassVar[ZPOOLProperty] = ...
    SIZE: ClassVar[ZPOOLProperty] = ...
    TNAME: ClassVar[ZPOOLProperty] = ...
    VERSION: ClassVar[ZPOOLProperty] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZPOOLStatus(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ZPOOL_STATUS_BAD_GUID_SUM: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_BAD_LOG: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_COMPATIBILITY_ERR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_CACHE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_DATA: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_LABEL_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_LABEL_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_POOL: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_ERRATA: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAILING_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAULTED_DEV_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAULTED_DEV_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FEAT_DISABLED: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_ACTIVE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_MISMATCH: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_REQUIRED: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_INCOMPATIBLE_FEAT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_CONTINUE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_MMP: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_WAIT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_MISSING_DEV_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_MISSING_DEV_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_NON_NATIVE_ASHIFT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_OFFLINE_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_OK: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REBUILDING: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REBUILD_SCRUB: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REMOVED_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_RESILVERING: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_UNSUP_FEAT_READ: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_UNSUP_FEAT_WRITE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_VERSION_NEWER: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_VERSION_OLDER: ClassVar[ZPOOLStatus] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

def open_handle(history=..., history_prefix=..., mnttab_cache=...) -> ZFS: ...


class ZFSPool:
    """Represents a ZFS pool."""
    @property
    def name(self) -> str:
        """Returns the name of the ZFS Pool."""
        ...

    def prefetch(self) -> None:
        """Prefetch pool metadata (DDT and BRT) into ARC."""
        ...

    def status(
        self,
        *,
        asdict: bool = ...,
        get_stats: bool = ...,
        follow_links: bool = ...,
        full_path: bool = ...,
    ) -> struct_zpool_status | dict: ...

    def get_features(self, *, asdict: bool = ...) -> dict[str, struct_zpool_feature] | dict[str, dict[str, str]]:
        """Return dict of pool features with their state and metadata."""
        ...


class struct_zfs_crypto_info:
    """Encryption status information for a ZFS dataset or volume."""
    is_root: bool
    """Whether this dataset is an encryption root."""
    encryption_root: str | None
    """Name of the encryption root dataset, or None if not encrypted."""
    key_location: str
    """The keylocation property value (e.g. 'prompt', 'file://...')."""
    key_is_loaded: bool
    """Whether the wrapping key is currently loaded."""


class ZFSCrypto:
    """Encryption operations for a ZFS dataset or volume."""

    def info(self) -> struct_zfs_crypto_info:
        """Return current encryption status information."""
        ...

    def load_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> None:
        """Load the encryption key for this dataset or volume.

        Pass ``key`` as ``str`` for hex and passphrase keyformats, or as
        ``bytes`` (exactly 32 bytes) for raw keyformat.  Mutually exclusive
        with ``key_location``.
        """
        ...

    def unload_key(self) -> None:
        """Unload the encryption key for this dataset or volume."""
        ...

    def check_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> bool:
        """Return True if the supplied key material can unlock this resource.

        Pass ``key`` as ``str`` for hex and passphrase keyformats, or as
        ``bytes`` (exactly 32 bytes) for raw keyformat.  Mutually exclusive
        with ``key_location``.
        """
        ...

    def change_key(self, *, info: Any) -> None:
        """Change the wrapping key and/or encryption properties.

        ``info`` must be a struct_zfs_crypto_config returned by
        ``ZFS.resource_cryptography_config()``.
        """
        ...

    def inherit_key(self) -> None:
        """Remove this dataset as an encryption root, inheriting from parent."""
        ...


class ZFS:
    def open_pool(self, *, name: str) -> ZFSPool:
        """Open a ZFS pool by name and return a ZFSPool object."""
        ...
    def open_resource(self, **kwargs) -> Any: ...
    def create_resource(self, *, name, type, properties=None, crypto=None) -> None: ...
    def destroy_pool(self, *, name, force=False) -> None: ...
    def destroy_resource(self, *, name) -> bool: ...
    def iter_pools(self, *, callback, state) -> bool: ...
    def iter_root_filesystems(self, *, callback, state) -> bool: ...
    def resource_cryptography_config(self, *, keyformat: str | None = None, keylocation: str | None = None, pbkdf2iters: int | None = None, key: str | bytes | None = None) -> Any: ...
    def zpool_events(self, *, blocking=False, skip_existing_events=True) -> Iterator[dict[str, Any]]: ...
