import enum
from typing import Callable, ClassVar

class VDevState(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CANT_OPEN: ClassVar[VDevState] = ...
    CLOSED: ClassVar[VDevState] = ...
    DEGRADED: ClassVar[VDevState] = ...
    FAULTED: ClassVar[VDevState] = ...
    OFFLINE: ClassVar[VDevState] = ...
    ONLINE: ClassVar[VDevState] = ...
    REMOVED: ClassVar[VDevState] = ...
    UNKNOWN: ClassVar[VDevState] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...
