import enum
from typing import Callable, ClassVar

class ScanFunction(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NONE: ClassVar[ScanFunction] = ...
    SCRUB: ClassVar[ScanFunction] = ...
    RESILVER: ClassVar[ScanFunction] = ...
    ERRORSCRUB: ClassVar[ScanFunction] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ScanState(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NONE: ClassVar[ScanState] = ...
    SCANNING: ClassVar[ScanState] = ...
    FINISHED: ClassVar[ScanState] = ...
    CANCELED: ClassVar[ScanState] = ...
    ERRORSCRUBBING: ClassVar[ScanState] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ScanScrubCmd(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NORMAL: ClassVar[ScanScrubCmd] = ...
    PAUSE: ClassVar[ScanScrubCmd] = ...
    FROM_LAST_TXG: ClassVar[ScanScrubCmd] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class VDevState(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CANT_OPEN: ClassVar[VDevState] = ...
    CLOSED: ClassVar[VDevState] = ...
    DEGRADED: ClassVar[VDevState] = ...
    FAULTED: ClassVar[VDevState] = ...
    OFFLINE: ClassVar[VDevState] = ...
    ONLINE: ClassVar[VDevState] = ...
    REMOVED: ClassVar[VDevState] = ...
    UNKNOWN: ClassVar[VDevState] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...
