from collections.abc import Iterable, Iterator, Sequence
import enum
from typing import Any, ClassVar, Literal


# ---------------------------------------------------------------------------
# Enums (dual-registered: also available at truenas_pylibzfs.<Name>)
# ---------------------------------------------------------------------------

class PropertySource(enum.IntFlag):
    DEFAULT: ClassVar[PropertySource] = ...
    INHERITED: ClassVar[PropertySource] = ...
    LOCAL: ClassVar[PropertySource] = ...
    NONE: ClassVar[PropertySource] = ...
    RECEIVED: ClassVar[PropertySource] = ...
    TEMPORARY: ClassVar[PropertySource] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ScanFunction(enum.IntEnum):
    NONE: ClassVar[ScanFunction] = ...
    SCRUB: ClassVar[ScanFunction] = ...
    RESILVER: ClassVar[ScanFunction] = ...
    ERRORSCRUB: ClassVar[ScanFunction] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ScanScrubCmd(enum.IntEnum):
    NORMAL: ClassVar[ScanScrubCmd] = ...
    PAUSE: ClassVar[ScanScrubCmd] = ...
    FROM_LAST_TXG: ClassVar[ScanScrubCmd] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ScanState(enum.IntEnum):
    NONE: ClassVar[ScanState] = ...
    SCANNING: ClassVar[ScanState] = ...
    FINISHED: ClassVar[ScanState] = ...
    CANCELED: ClassVar[ScanState] = ...
    ERRORSCRUBBING: ClassVar[ScanState] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class VDevAuxState(enum.IntEnum):
    VDEV_AUX_ACTIVE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_ASHIFT_TOO_BIG: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_ASHIFT: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_GUID_SUM: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_LABEL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_BAD_LOG: ClassVar[VDevAuxState] = ...
    VDEV_AUX_CHILDREN_OFFLINE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_CORRUPT_DATA: ClassVar[VDevAuxState] = ...
    VDEV_AUX_ERR_EXCEEDED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_EXTERNAL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_EXTERNAL_PERSIST: ClassVar[VDevAuxState] = ...
    VDEV_AUX_IO_FAILURE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_NONE: ClassVar[VDevAuxState] = ...
    VDEV_AUX_NO_REPLICAS: ClassVar[VDevAuxState] = ...
    VDEV_AUX_OPEN_FAILED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_SPARED: ClassVar[VDevAuxState] = ...
    VDEV_AUX_SPLIT_POOL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_TOO_SMALL: ClassVar[VDevAuxState] = ...
    VDEV_AUX_UNSUP_FEAT: ClassVar[VDevAuxState] = ...
    VDEV_AUX_VERSION_NEWER: ClassVar[VDevAuxState] = ...
    VDEV_AUX_VERSION_OLDER: ClassVar[VDevAuxState] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class VDevState(enum.IntEnum):
    CANT_OPEN: ClassVar[VDevState] = ...
    CLOSED: ClassVar[VDevState] = ...
    DEGRADED: ClassVar[VDevState] = ...
    FAULTED: ClassVar[VDevState] = ...
    OFFLINE: ClassVar[VDevState] = ...
    ONLINE: ClassVar[VDevState] = ...
    REMOVED: ClassVar[VDevState] = ...
    UNKNOWN: ClassVar[VDevState] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class VDevType(enum.StrEnum):
    """Vdev type for use with create_vdev_spec()."""
    DISK: ClassVar[VDevType] = ...
    FILE: ClassVar[VDevType] = ...
    MIRROR: ClassVar[VDevType] = ...
    RAIDZ1: ClassVar[VDevType] = ...
    RAIDZ2: ClassVar[VDevType] = ...
    RAIDZ3: ClassVar[VDevType] = ...
    DRAID1: ClassVar[VDevType] = ...
    DRAID2: ClassVar[VDevType] = ...
    DRAID3: ClassVar[VDevType] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSDOSFlag(enum.IntFlag):
    ZFS_APPENDONLY: ClassVar[ZFSDOSFlag] = ...
    ZFS_ARCHIVE: ClassVar[ZFSDOSFlag] = ...
    ZFS_HIDDEN: ClassVar[ZFSDOSFlag] = ...
    ZFS_IMMUTABLE: ClassVar[ZFSDOSFlag] = ...
    ZFS_NODUMP: ClassVar[ZFSDOSFlag] = ...
    ZFS_NOUNLINK: ClassVar[ZFSDOSFlag] = ...
    ZFS_READONLY: ClassVar[ZFSDOSFlag] = ...
    ZFS_SPARSE: ClassVar[ZFSDOSFlag] = ...
    ZFS_SYSTEM: ClassVar[ZFSDOSFlag] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSError(enum.IntEnum):
    EZFS_ACTIVE_POOL: ClassVar[ZFSError] = ...
    EZFS_ACTIVE_SPARE: ClassVar[ZFSError] = ...
    EZFS_ASHIFT_MISMATCH: ClassVar[ZFSError] = ...
    EZFS_BADBACKUP: ClassVar[ZFSError] = ...
    EZFS_BADCACHE: ClassVar[ZFSError] = ...
    EZFS_BADDEV: ClassVar[ZFSError] = ...
    EZFS_BADPATH: ClassVar[ZFSError] = ...
    EZFS_BADPERM: ClassVar[ZFSError] = ...
    EZFS_BADPERMSET: ClassVar[ZFSError] = ...
    EZFS_BADPROP: ClassVar[ZFSError] = ...
    EZFS_BADRESTORE: ClassVar[ZFSError] = ...
    EZFS_BADSTREAM: ClassVar[ZFSError] = ...
    EZFS_BADTARGET: ClassVar[ZFSError] = ...
    EZFS_BADTYPE: ClassVar[ZFSError] = ...
    EZFS_BADVERSION: ClassVar[ZFSError] = ...
    EZFS_BADWHO: ClassVar[ZFSError] = ...
    EZFS_BUSY: ClassVar[ZFSError] = ...
    EZFS_CHECKPOINT_EXISTS: ClassVar[ZFSError] = ...
    EZFS_CKSUM: ClassVar[ZFSError] = ...
    EZFS_CROSSTARGET: ClassVar[ZFSError] = ...
    EZFS_CRYPTOFAILED: ClassVar[ZFSError] = ...
    EZFS_DEVOVERFLOW: ClassVar[ZFSError] = ...
    EZFS_DEVRM_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_DIFF: ClassVar[ZFSError] = ...
    EZFS_DIFFDATA: ClassVar[ZFSError] = ...
    EZFS_DISCARDING_CHECKPOINT: ClassVar[ZFSError] = ...
    EZFS_DSREADONLY: ClassVar[ZFSError] = ...
    EZFS_ERRORSCRUBBING: ClassVar[ZFSError] = ...
    EZFS_ERRORSCRUB_PAUSED: ClassVar[ZFSError] = ...
    EZFS_EXISTS: ClassVar[ZFSError] = ...
    EZFS_EXPORT_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_FAULT: ClassVar[ZFSError] = ...
    EZFS_INITIALIZING: ClassVar[ZFSError] = ...
    EZFS_INTR: ClassVar[ZFSError] = ...
    EZFS_INVALCONFIG: ClassVar[ZFSError] = ...
    EZFS_INVALIDNAME: ClassVar[ZFSError] = ...
    EZFS_IO: ClassVar[ZFSError] = ...
    EZFS_IOC_NOTSUPPORTED: ClassVar[ZFSError] = ...
    EZFS_ISL2CACHE: ClassVar[ZFSError] = ...
    EZFS_ISSPARE: ClassVar[ZFSError] = ...
    EZFS_LABELFAILED: ClassVar[ZFSError] = ...
    EZFS_MOUNTFAILED: ClassVar[ZFSError] = ...
    EZFS_NAMETOOLONG: ClassVar[ZFSError] = ...
    EZFS_NOCAP: ClassVar[ZFSError] = ...
    EZFS_NODELEGATION: ClassVar[ZFSError] = ...
    EZFS_NODEVICE: ClassVar[ZFSError] = ...
    EZFS_NOENT: ClassVar[ZFSError] = ...
    EZFS_NOHISTORY: ClassVar[ZFSError] = ...
    EZFS_NOMEM: ClassVar[ZFSError] = ...
    EZFS_NOREPLICAS: ClassVar[ZFSError] = ...
    EZFS_NOSPC: ClassVar[ZFSError] = ...
    EZFS_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_NOT_USER_NAMESPACE: ClassVar[ZFSError] = ...
    EZFS_NO_CHECKPOINT: ClassVar[ZFSError] = ...
    EZFS_NO_INITIALIZE: ClassVar[ZFSError] = ...
    EZFS_NO_PENDING: ClassVar[ZFSError] = ...
    EZFS_NO_RESILVER_DEFER: ClassVar[ZFSError] = ...
    EZFS_NO_SCRUB: ClassVar[ZFSError] = ...
    EZFS_NO_TRIM: ClassVar[ZFSError] = ...
    EZFS_OPENFAILED: ClassVar[ZFSError] = ...
    EZFS_PERM: ClassVar[ZFSError] = ...
    EZFS_PIPEFAILED: ClassVar[ZFSError] = ...
    EZFS_POOLPROPS: ClassVar[ZFSError] = ...
    EZFS_POOLREADONLY: ClassVar[ZFSError] = ...
    EZFS_POOLUNAVAIL: ClassVar[ZFSError] = ...
    EZFS_POOL_INVALARG: ClassVar[ZFSError] = ...
    EZFS_POOL_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_POSTSPLIT_ONLINE: ClassVar[ZFSError] = ...
    EZFS_PROPNONINHERIT: ClassVar[ZFSError] = ...
    EZFS_PROPREADONLY: ClassVar[ZFSError] = ...
    EZFS_PROPSPACE: ClassVar[ZFSError] = ...
    EZFS_PROPTYPE: ClassVar[ZFSError] = ...
    EZFS_RAIDZ_EXPAND_IN_PROGRESS: ClassVar[ZFSError] = ...
    EZFS_REBUILDING: ClassVar[ZFSError] = ...
    EZFS_RECURSIVE: ClassVar[ZFSError] = ...
    EZFS_REFTAG_HOLD: ClassVar[ZFSError] = ...
    EZFS_REFTAG_RELE: ClassVar[ZFSError] = ...
    EZFS_RESILVERING: ClassVar[ZFSError] = ...
    EZFS_RESUME_EXISTS: ClassVar[ZFSError] = ...
    EZFS_SCRUBBING: ClassVar[ZFSError] = ...
    EZFS_SCRUB_PAUSED: ClassVar[ZFSError] = ...
    EZFS_SCRUB_PAUSED_TO_CANCEL: ClassVar[ZFSError] = ...
    EZFS_SHAREFAILED: ClassVar[ZFSError] = ...
    EZFS_SHARENFSFAILED: ClassVar[ZFSError] = ...
    EZFS_SHARESMBFAILED: ClassVar[ZFSError] = ...
    EZFS_SUCCESS: ClassVar[ZFSError] = ...
    EZFS_TAGTOOLONG: ClassVar[ZFSError] = ...
    EZFS_THREADCREATEFAILED: ClassVar[ZFSError] = ...
    EZFS_TOOMANY: ClassVar[ZFSError] = ...
    EZFS_TRIMMING: ClassVar[ZFSError] = ...
    EZFS_TRIM_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_UMOUNTFAILED: ClassVar[ZFSError] = ...
    EZFS_UNKNOWN: ClassVar[ZFSError] = ...
    EZFS_UNPLAYED_LOGS: ClassVar[ZFSError] = ...
    EZFS_UNSHARENFSFAILED: ClassVar[ZFSError] = ...
    EZFS_UNSHARESMBFAILED: ClassVar[ZFSError] = ...
    EZFS_VDEVNOTSUP: ClassVar[ZFSError] = ...
    EZFS_VDEV_NOTSUP: ClassVar[ZFSError] = ...
    EZFS_VDEV_TOO_BIG: ClassVar[ZFSError] = ...
    EZFS_VOLTOOBIG: ClassVar[ZFSError] = ...
    EZFS_WRONG_PARENT: ClassVar[ZFSError] = ...
    EZFS_ZONED: ClassVar[ZFSError] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSProperty(enum.IntEnum):
    ACLINHERIT: ClassVar[ZFSProperty] = ...
    ACLMODE: ClassVar[ZFSProperty] = ...
    ACLTYPE: ClassVar[ZFSProperty] = ...
    ATIME: ClassVar[ZFSProperty] = ...
    AVAILABLE: ClassVar[ZFSProperty] = ...
    CANMOUNT: ClassVar[ZFSProperty] = ...
    CASESENSITIVITY: ClassVar[ZFSProperty] = ...
    CHECKSUM: ClassVar[ZFSProperty] = ...
    CLONES: ClassVar[ZFSProperty] = ...
    COMPRESSION: ClassVar[ZFSProperty] = ...
    COMPRESSRATIO: ClassVar[ZFSProperty] = ...
    CONTEXT: ClassVar[ZFSProperty] = ...
    COPIES: ClassVar[ZFSProperty] = ...
    CREATETXG: ClassVar[ZFSProperty] = ...
    CREATION: ClassVar[ZFSProperty] = ...
    DEDUP: ClassVar[ZFSProperty] = ...
    DEFAULTGROUPOBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTGROUPQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTPROJECTOBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTPROJECTQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTUSEROBJQUOTA: ClassVar[ZFSProperty] = ...
    DEFAULTUSERQUOTA: ClassVar[ZFSProperty] = ...
    DEFCONTEXT: ClassVar[ZFSProperty] = ...
    DEFER_DESTROY: ClassVar[ZFSProperty] = ...
    DEVICES: ClassVar[ZFSProperty] = ...
    DIRECT: ClassVar[ZFSProperty] = ...
    DNODESIZE: ClassVar[ZFSProperty] = ...
    ENCRYPTION: ClassVar[ZFSProperty] = ...
    ENCRYPTIONROOT: ClassVar[ZFSProperty] = ...
    EXEC: ClassVar[ZFSProperty] = ...
    FILESYSTEM_COUNT: ClassVar[ZFSProperty] = ...
    FILESYSTEM_LIMIT: ClassVar[ZFSProperty] = ...
    FSCONTEXT: ClassVar[ZFSProperty] = ...
    GUID: ClassVar[ZFSProperty] = ...
    KEYFORMAT: ClassVar[ZFSProperty] = ...
    KEYLOCATION: ClassVar[ZFSProperty] = ...
    KEYSTATUS: ClassVar[ZFSProperty] = ...
    LOGBIAS: ClassVar[ZFSProperty] = ...
    LOGICALREFERENCED: ClassVar[ZFSProperty] = ...
    LOGICALUSED: ClassVar[ZFSProperty] = ...
    LONGNAME: ClassVar[ZFSProperty] = ...
    MLSLABEL: ClassVar[ZFSProperty] = ...
    MOUNTED: ClassVar[ZFSProperty] = ...
    MOUNTPOINT: ClassVar[ZFSProperty] = ...
    NBMAND: ClassVar[ZFSProperty] = ...
    NORMALIZATION: ClassVar[ZFSProperty] = ...
    OBJSETID: ClassVar[ZFSProperty] = ...
    ORIGIN: ClassVar[ZFSProperty] = ...
    OVERLAY: ClassVar[ZFSProperty] = ...
    PBKDF2ITERS: ClassVar[ZFSProperty] = ...
    PREFETCH: ClassVar[ZFSProperty] = ...
    PRIMARYCACHE: ClassVar[ZFSProperty] = ...
    QUOTA: ClassVar[ZFSProperty] = ...
    READONLY: ClassVar[ZFSProperty] = ...
    RECEIVE_RESUME_TOKEN: ClassVar[ZFSProperty] = ...
    RECORDSIZE: ClassVar[ZFSProperty] = ...
    REDACT_SNAPS: ClassVar[ZFSProperty] = ...
    REDUNDANT_METADATA: ClassVar[ZFSProperty] = ...
    REFCOMPRESSRATIO: ClassVar[ZFSProperty] = ...
    REFERENCED: ClassVar[ZFSProperty] = ...
    REFQUOTA: ClassVar[ZFSProperty] = ...
    REFRESERVATION: ClassVar[ZFSProperty] = ...
    RELATIME: ClassVar[ZFSProperty] = ...
    RESERVATION: ClassVar[ZFSProperty] = ...
    ROOTCONTEXT: ClassVar[ZFSProperty] = ...
    SECONDARYCACHE: ClassVar[ZFSProperty] = ...
    SETUID: ClassVar[ZFSProperty] = ...
    SHARENFS: ClassVar[ZFSProperty] = ...
    SHARESMB: ClassVar[ZFSProperty] = ...
    SNAPDEV: ClassVar[ZFSProperty] = ...
    SNAPDIR: ClassVar[ZFSProperty] = ...
    SNAPSHOTS_CHANGED: ClassVar[ZFSProperty] = ...
    SNAPSHOT_COUNT: ClassVar[ZFSProperty] = ...
    SNAPSHOT_LIMIT: ClassVar[ZFSProperty] = ...
    SPECIAL_SMALL_BLOCKS: ClassVar[ZFSProperty] = ...
    SYNC: ClassVar[ZFSProperty] = ...
    TYPE: ClassVar[ZFSProperty] = ...
    USED: ClassVar[ZFSProperty] = ...
    USEDBYCHILDREN: ClassVar[ZFSProperty] = ...
    USEDBYDATASET: ClassVar[ZFSProperty] = ...
    USEDBYREFRESERVATION: ClassVar[ZFSProperty] = ...
    USEDBYSNAPSHOTS: ClassVar[ZFSProperty] = ...
    USERREFS: ClassVar[ZFSProperty] = ...
    UTF8ONLY: ClassVar[ZFSProperty] = ...
    VERSION: ClassVar[ZFSProperty] = ...
    VOLBLOCKSIZE: ClassVar[ZFSProperty] = ...
    VOLMODE: ClassVar[ZFSProperty] = ...
    VOLSIZE: ClassVar[ZFSProperty] = ...
    VOLTHREADING: ClassVar[ZFSProperty] = ...
    VSCAN: ClassVar[ZFSProperty] = ...
    WRITTEN: ClassVar[ZFSProperty] = ...
    XATTR: ClassVar[ZFSProperty] = ...
    ZONED: ClassVar[ZFSProperty] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSType(enum.IntEnum):
    ZFS_TYPE_BOOKMARK: ClassVar[ZFSType] = ...
    ZFS_TYPE_FILESYSTEM: ClassVar[ZFSType] = ...
    ZFS_TYPE_INVALID: ClassVar[ZFSType] = ...
    ZFS_TYPE_POOL: ClassVar[ZFSType] = ...
    ZFS_TYPE_SNAPSHOT: ClassVar[ZFSType] = ...
    ZFS_TYPE_VDEV: ClassVar[ZFSType] = ...
    ZFS_TYPE_VOLUME: ClassVar[ZFSType] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZFSUserQuota(enum.IntEnum):
    GROUPOBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    GROUPOBJ_USED: ClassVar[ZFSUserQuota] = ...
    GROUP_QUOTA: ClassVar[ZFSUserQuota] = ...
    GROUP_USED: ClassVar[ZFSUserQuota] = ...
    PROJECTOBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    PROJECTOBJ_USED: ClassVar[ZFSUserQuota] = ...
    PROJECT_QUOTA: ClassVar[ZFSUserQuota] = ...
    PROJECT_USED: ClassVar[ZFSUserQuota] = ...
    USEROBJ_QUOTA: ClassVar[ZFSUserQuota] = ...
    USEROBJ_USED: ClassVar[ZFSUserQuota] = ...
    USER_QUOTA: ClassVar[ZFSUserQuota] = ...
    USER_USED: ClassVar[ZFSUserQuota] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZPOOLProperty(enum.IntEnum):
    ALLOCATED: ClassVar[ZPOOLProperty] = ...
    ALTROOT: ClassVar[ZPOOLProperty] = ...
    ASHIFT: ClassVar[ZPOOLProperty] = ...
    AUTOEXPAND: ClassVar[ZPOOLProperty] = ...
    AUTOREPLACE: ClassVar[ZPOOLProperty] = ...
    AUTOTRIM: ClassVar[ZPOOLProperty] = ...
    AVAILABLE: ClassVar[ZPOOLProperty] = ...
    BCLONERATIO: ClassVar[ZPOOLProperty] = ...
    BCLONESAVED: ClassVar[ZPOOLProperty] = ...
    BCLONEUSED: ClassVar[ZPOOLProperty] = ...
    BOOTFS: ClassVar[ZPOOLProperty] = ...
    CACHEFILE: ClassVar[ZPOOLProperty] = ...
    CAPACITY: ClassVar[ZPOOLProperty] = ...
    CHECKPOINT: ClassVar[ZPOOLProperty] = ...
    COMMENT: ClassVar[ZPOOLProperty] = ...
    COMPATIBILITY: ClassVar[ZPOOLProperty] = ...
    DEDUPCACHED: ClassVar[ZPOOLProperty] = ...
    DEDUPDITTO: ClassVar[ZPOOLProperty] = ...
    DEDUPRATIO: ClassVar[ZPOOLProperty] = ...
    DEDUP_TABLE_QUOTA: ClassVar[ZPOOLProperty] = ...
    DEDUP_TABLE_SIZE: ClassVar[ZPOOLProperty] = ...
    DEDUPSAVED: ClassVar[ZPOOLProperty] = ...
    DEDUPUSED: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_DEDUP_USED: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_ELOG_USED: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_LOG_USED: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_NORMAL_USED: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_ALLOCATED: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_AVAILABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_CAPACITY: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_ELOG_USED: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_FREE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_SIZE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_USABLE: ClassVar[ZPOOLProperty] = ...
    CLASS_SPECIAL_USED: ClassVar[ZPOOLProperty] = ...
    DELEGATION: ClassVar[ZPOOLProperty] = ...
    EXPANDSIZE: ClassVar[ZPOOLProperty] = ...
    FAILMODE: ClassVar[ZPOOLProperty] = ...
    FRAGMENTATION: ClassVar[ZPOOLProperty] = ...
    FREE: ClassVar[ZPOOLProperty] = ...
    FREEING: ClassVar[ZPOOLProperty] = ...
    GUID: ClassVar[ZPOOLProperty] = ...
    HEALTH: ClassVar[ZPOOLProperty] = ...
    INVAL: ClassVar[ZPOOLProperty] = ...
    LAST_SCRUBBED_TXG: ClassVar[ZPOOLProperty] = ...
    LEAKED: ClassVar[ZPOOLProperty] = ...
    LISTSNAPSHOTS: ClassVar[ZPOOLProperty] = ...
    LOAD_GUID: ClassVar[ZPOOLProperty] = ...
    MAXBLOCKSIZE: ClassVar[ZPOOLProperty] = ...
    MAXDNODESIZE: ClassVar[ZPOOLProperty] = ...
    MULTIHOST: ClassVar[ZPOOLProperty] = ...
    NAME: ClassVar[ZPOOLProperty] = ...
    READONLY: ClassVar[ZPOOLProperty] = ...
    SIZE: ClassVar[ZPOOLProperty] = ...
    TNAME: ClassVar[ZPOOLProperty] = ...
    USABLE: ClassVar[ZPOOLProperty] = ...
    USED: ClassVar[ZPOOLProperty] = ...
    VERSION: ClassVar[ZPOOLProperty] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class ZPOOLStatus(enum.IntEnum):
    ZPOOL_STATUS_BAD_GUID_SUM: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_BAD_LOG: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_COMPATIBILITY_ERR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_CACHE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_DATA: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_LABEL_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_LABEL_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_CORRUPT_POOL: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_ERRATA: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAILING_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAULTED_DEV_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FAULTED_DEV_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_FEAT_DISABLED: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_ACTIVE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_MISMATCH: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_HOSTID_REQUIRED: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_INCOMPATIBLE_FEAT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_CONTINUE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_MMP: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_IO_FAILURE_WAIT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_MISSING_DEV_NR: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_MISSING_DEV_R: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_NON_NATIVE_ASHIFT: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_OFFLINE_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_OK: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REBUILDING: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REBUILD_SCRUB: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_REMOVED_DEV: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_RESILVERING: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_UNSUP_FEAT_READ: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_UNSUP_FEAT_WRITE: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_VERSION_NEWER: ClassVar[ZPOOLStatus] = ...
    ZPOOL_STATUS_VERSION_OLDER: ClassVar[ZPOOLStatus] = ...
    def __format__(self, *args, **kwargs) -> str: ...


# ---------------------------------------------------------------------------
# Struct sequence types
# ---------------------------------------------------------------------------

class struct_vdev_create_spec:
    """Vdev creation specification for use with ZFS.create_pool()."""
    name: str | None
    vdev_type: VDevType | str
    children: tuple[struct_vdev_create_spec, ...] | None

class struct_vdev_stats:
    timestamp: int
    allocated: int
    space: int
    dspace: int
    pspace: int
    rsize: int
    esize: int
    read_errors: int
    write_errors: int
    checksum_errors: int
    initialize_errors: int
    dio_verify_errors: int
    slow_ios: int | None
    self_healed_bytes: int
    fragmentation: int | None
    scan_processed: int
    scan_removing: int
    rebuild_processed: int
    noalloc: int | None
    ops_read: int
    ops_write: int
    bytes_read: int
    bytes_write: int
    configured_ashift: int | None
    logical_ashift: int | None
    physical_ashift: int | None

class struct_vdev:
    name: str
    vdev_type: str
    guid: int
    state: VDevState
    stats: struct_vdev_stats | None
    children: tuple[struct_vdev, ...] | None
    top_guid: int | None

class struct_support_vdev:
    cache: tuple[struct_vdev, ...]
    log: tuple[struct_vdev, ...]
    special: tuple[struct_vdev, ...]
    dedup: tuple[struct_vdev, ...]

class struct_zpool_feature:
    guid: str
    description: str
    state: Literal["DISABLED", "ENABLED", "ACTIVE"]

class struct_zpool_scrub:
    func: ScanFunction
    state: ScanState
    start_time: int
    end_time: int
    to_examine: int
    examined: int
    skipped: int
    processed: int
    issued: int
    errors: int
    pass_exam: int
    pass_start: int
    pass_scrub_pause: int
    pass_scrub_spent_paused: int
    pass_issued: int
    error_scrub_func: ScanFunction | None
    error_scrub_state: ScanState | None
    error_scrub_start: int | None
    error_scrub_end: int | None
    error_scrub_examined: int | None
    error_scrub_to_be_examined: int | None
    pass_error_scrub_pause: int | None
    percentage: float | None

class struct_zpool_expand:
    state: ScanState
    expanding_vdev: int
    start_time: int
    end_time: int
    to_reflow: int
    reflowed: int
    waiting_for_resilver: int

class struct_zpool_status:
    status: ZPOOLStatus
    reason: str | None
    action: str | None
    message: str | None
    corrupted_files: tuple[str, ...]
    storage_vdevs: tuple[struct_vdev, ...]
    support_vdevs: struct_support_vdev
    spares: tuple[struct_vdev, ...]
    name: str
    guid: int

class struct_zfs_property_source:
    """Source information for a ZFS or pool property."""
    type: PropertySource
    value: str | None

class struct_zfs_property_data:
    """Individual property value and source information."""
    value: int | str | None
    raw: str
    source: struct_zfs_property_source | None

class struct_zpool_property_data:
    """Per-property data returned by ZFSPool.get_properties()."""
    prop: ZPOOLProperty
    value: int | str | None
    raw: str
    source: PropertySource | None

class struct_zpool_property:
    """Pool property bundle returned by ZFSPool.get_properties().

    Each attribute corresponds to a ZPOOLProperty member.
    Requested properties contain the parsed value directly (int for numeric
    properties, str for string/index properties); unrequested properties
    are None.

    Attribute names are the lowercase libzfs property names as returned by
    zpool_prop_to_name() (e.g. ``failmode``, ``listsnapshots``,
    ``expandsize``).  These differ from the ZPOOLProperty enum member names.
    """
    name:                         struct_zpool_property_data | None
    size:                         struct_zpool_property_data | None
    capacity:                     struct_zpool_property_data | None
    altroot:                      struct_zpool_property_data | None
    health:                       struct_zpool_property_data | None
    guid:                         struct_zpool_property_data | None
    version:                      struct_zpool_property_data | None
    bootfs:                       struct_zpool_property_data | None
    delegation:                   struct_zpool_property_data | None
    autoreplace:                  struct_zpool_property_data | None
    cachefile:                    struct_zpool_property_data | None
    failmode:                     struct_zpool_property_data | None
    listsnapshots:                struct_zpool_property_data | None
    autoexpand:                   struct_zpool_property_data | None
    dedupditto:                   struct_zpool_property_data | None
    dedupratio:                   struct_zpool_property_data | None
    free:                         struct_zpool_property_data | None
    allocated:                    struct_zpool_property_data | None
    readonly:                     struct_zpool_property_data | None
    ashift:                       struct_zpool_property_data | None
    comment:                      struct_zpool_property_data | None
    expandsize:                   struct_zpool_property_data | None
    freeing:                      struct_zpool_property_data | None
    fragmentation:                struct_zpool_property_data | None
    leaked:                       struct_zpool_property_data | None
    maxblocksize:                 struct_zpool_property_data | None
    tname:                        struct_zpool_property_data | None
    maxdnodesize:                 struct_zpool_property_data | None
    multihost:                    struct_zpool_property_data | None
    checkpoint:                   struct_zpool_property_data | None
    load_guid:                    struct_zpool_property_data | None
    autotrim:                     struct_zpool_property_data | None
    compatibility:                struct_zpool_property_data | None
    bcloneused:                   struct_zpool_property_data | None
    bclonesaved:                  struct_zpool_property_data | None
    bcloneratio:                  struct_zpool_property_data | None
    dedup_table_size:             struct_zpool_property_data | None
    dedup_table_quota:            struct_zpool_property_data | None
    dedupcached:                  struct_zpool_property_data | None
    last_scrubbed_txg:            struct_zpool_property_data | None
    dedupused:                    struct_zpool_property_data | None
    dedupsaved:                   struct_zpool_property_data | None
    available:                    struct_zpool_property_data | None
    usable:                       struct_zpool_property_data | None
    used:                         struct_zpool_property_data | None
    class_normal_size:            struct_zpool_property_data | None
    class_normal_capacity:        struct_zpool_property_data | None
    class_normal_free:            struct_zpool_property_data | None
    class_normal_allocated:       struct_zpool_property_data | None
    class_normal_available:       struct_zpool_property_data | None
    class_normal_usable:          struct_zpool_property_data | None
    class_normal_used:            struct_zpool_property_data | None
    class_normal_expandsize:      struct_zpool_property_data | None
    class_normal_fragmentation:   struct_zpool_property_data | None
    class_special_size:           struct_zpool_property_data | None
    class_special_capacity:       struct_zpool_property_data | None
    class_special_free:           struct_zpool_property_data | None
    class_special_allocated:      struct_zpool_property_data | None
    class_special_available:      struct_zpool_property_data | None
    class_special_usable:         struct_zpool_property_data | None
    class_special_used:           struct_zpool_property_data | None
    class_special_expandsize:     struct_zpool_property_data | None
    class_special_fragmentation:  struct_zpool_property_data | None
    class_dedup_size:             struct_zpool_property_data | None
    class_dedup_capacity:         struct_zpool_property_data | None
    class_dedup_free:             struct_zpool_property_data | None
    class_dedup_allocated:        struct_zpool_property_data | None
    class_dedup_available:        struct_zpool_property_data | None
    class_dedup_usable:           struct_zpool_property_data | None
    class_dedup_used:             struct_zpool_property_data | None
    class_dedup_expandsize:       struct_zpool_property_data | None
    class_dedup_fragmentation:    struct_zpool_property_data | None
    class_log_size:               struct_zpool_property_data | None
    class_log_capacity:           struct_zpool_property_data | None
    class_log_free:               struct_zpool_property_data | None
    class_log_allocated:          struct_zpool_property_data | None
    class_log_available:          struct_zpool_property_data | None
    class_log_usable:             struct_zpool_property_data | None
    class_log_used:               struct_zpool_property_data | None
    class_log_expandsize:         struct_zpool_property_data | None
    class_log_fragmentation:      struct_zpool_property_data | None
    class_elog_size:              struct_zpool_property_data | None
    class_elog_capacity:          struct_zpool_property_data | None
    class_elog_free:              struct_zpool_property_data | None
    class_elog_allocated:         struct_zpool_property_data | None
    class_elog_available:         struct_zpool_property_data | None
    class_elog_usable:            struct_zpool_property_data | None
    class_elog_used:              struct_zpool_property_data | None
    class_elog_expandsize:        struct_zpool_property_data | None
    class_elog_fragmentation:     struct_zpool_property_data | None
    class_special_elog_size:          struct_zpool_property_data | None
    class_special_elog_capacity:      struct_zpool_property_data | None
    class_special_elog_free:          struct_zpool_property_data | None
    class_special_elog_allocated:     struct_zpool_property_data | None
    class_special_elog_available:     struct_zpool_property_data | None
    class_special_elog_usable:        struct_zpool_property_data | None
    class_special_elog_used:          struct_zpool_property_data | None
    class_special_elog_expandsize:    struct_zpool_property_data | None
    class_special_elog_fragmentation: struct_zpool_property_data | None

class struct_zfs_crypto_info:
    """Encryption status information for a ZFS dataset or volume."""
    is_root: bool
    """Whether this dataset is an encryption root."""
    encryption_root: str | None
    """Name of the encryption root dataset, or None if not encrypted."""
    key_location: str
    """The keylocation property value (e.g. 'prompt', 'file://...')."""
    key_is_loaded: bool
    """Whether the wrapping key is currently loaded."""


# ---------------------------------------------------------------------------
# C extension types (not directly instantiable; use factories)
# ---------------------------------------------------------------------------

class ZFSCrypto:
    """Encryption operations for a ZFS dataset or volume."""

    def info(self) -> struct_zfs_crypto_info: ...

    def load_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> None: ...

    def unload_key(self) -> None: ...

    def check_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> bool: ...

    def change_key(self, *, info: Any) -> None: ...

    def inherit_key(self) -> None: ...


class ZFSSnapshot:
    def get_holds(self) -> tuple: ...
    def get_clones(self) -> tuple: ...
    def clone(self, *, name: str, properties: dict | None = None) -> None: ...


class ZFSPool:
    """Represents a ZFS pool."""
    @property
    def name(self) -> str: ...

    def prefetch(self) -> None: ...

    def status(
        self,
        *,
        asdict: bool = ...,
        get_stats: bool = ...,
        follow_links: bool = ...,
        full_path: bool = ...,
    ) -> struct_zpool_status | dict: ...

    def get_features(self, *, asdict: bool = ...) -> dict[str, struct_zpool_feature] | dict[str, dict[str, str]]: ...

    def scrub_info(self) -> struct_zpool_scrub | None: ...

    def expand_info(self) -> struct_zpool_expand | None: ...

    def scan(self, *, func: ScanFunction, cmd: ScanScrubCmd = ...) -> None: ...

    def get_properties(self, *, properties: set) -> struct_zpool_property: ...

    def set_properties(self, *, properties: dict) -> None: ...

    def get_user_properties(self) -> dict[str, str]: ...

    def set_user_properties(self, *, user_properties: dict[str, str]) -> None: ...

    def offline_device(self, *, device: str, temporary: bool = False) -> None: ...

    def online_device(self, *, device: str, expand: bool = False) -> None: ...

    def add_vdevs(
        self,
        *,
        storage_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        cache_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        log_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        special_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        dedup_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        spare_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        force: bool = False,
    ) -> None: ...

    def attach_vdev(
        self,
        *,
        device: str,
        new_device: struct_vdev_create_spec,
        rebuild: bool = False,
        force: bool = False,
    ) -> None: ...

    def replace_vdev(
        self,
        *,
        device: str,
        new_device: struct_vdev_create_spec | None = None,
        rebuild: bool = False,
    ) -> None: ...

    def detach_vdev(self, *, device: str) -> None: ...

    def remove_vdev(self, *, device: str) -> None: ...

    def cancel_remove_vdev(self) -> None: ...

    def iter_history(
        self,
        *,
        skip_internal: bool = True,
        since: int = 0,
        until: int = 0,
    ) -> Iterator[dict]: ...


class ZFS:
    """ZFS library handle. Obtain via truenas_pylibzfs.open_handle()."""
    def open_pool(self, *, name: str) -> ZFSPool: ...
    def open_resource(self, **kwargs) -> Any: ...
    def create_resource(self, *, name: str, type: ZFSType, properties: dict | None = None, crypto: Any | None = None) -> None: ...
    def create_pool(
        self,
        *,
        name: str,
        storage_vdevs: Iterable[struct_vdev_create_spec],
        cache_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        log_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        special_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        dedup_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        spare_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        properties: dict[ZPOOLProperty, str] | None = None,
        filesystem_properties: dict[ZFSProperty, str] | None = None,
        force: bool = False,
    ) -> None: ...
    def destroy_pool(self, *, name: str, force: bool = False) -> None: ...
    def export_pool(self, *, name: str, force: bool = False) -> None: ...
    def destroy_resource(self, *, name: str) -> bool: ...
    def iter_pools(self, *, callback: Any, state: Any) -> bool: ...
    def iter_root_filesystems(self, *, callback: Any, state: Any) -> bool: ...
    def resource_cryptography_config(self, *, keyformat: str | None = None, keylocation: str | None = None, pbkdf2iters: int | None = None, key: str | bytes | None = None) -> Any: ...
    def zpool_events(self, *, blocking: bool = False, skip_existing_events: bool = True) -> Iterator[dict[str, Any]]: ...
    def import_pool_find(self, *, cache_file: str | None = None, device: str | None = None) -> list[struct_zpool_status]: ...
    def import_pool(self, *, name: str | None = None, guid: int | None = None,
                    allow_missing_log: bool = False, altroot: str | None = None,
                    force: bool = False, properties: dict[ZPOOLProperty | str, str] | None = None,
                    temporary_name: str | None = None, device: str | None = None) -> ZFSPool: ...
