from collections.abc import Iterable, Iterator, Sequence
import enum
from typing import Any, Literal


# ---------------------------------------------------------------------------
# Enums (dual-registered: also available at truenas_pylibzfs.<Name>)
# ---------------------------------------------------------------------------

class PropertySource(enum.IntFlag):
    DEFAULT = ...
    INHERITED = ...
    LOCAL = ...
    NONE = ...
    RECEIVED = ...
    TEMPORARY = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ScanFunction(enum.IntEnum):
    NONE = ...
    SCRUB = ...
    RESILVER = ...
    ERRORSCRUB = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ScanScrubCmd(enum.IntEnum):
    NORMAL = ...
    PAUSE = ...
    FROM_LAST_TXG = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ScanState(enum.IntEnum):
    NONE = ...
    SCANNING = ...
    FINISHED = ...
    CANCELED = ...
    ERRORSCRUBBING = ...
    def __format__(self, format_spec: str, /) -> str: ...

class VDevAuxState(enum.IntEnum):
    VDEV_AUX_ACTIVE = ...
    VDEV_AUX_ASHIFT_TOO_BIG = ...
    VDEV_AUX_BAD_ASHIFT = ...
    VDEV_AUX_BAD_GUID_SUM = ...
    VDEV_AUX_BAD_LABEL = ...
    VDEV_AUX_BAD_LOG = ...
    VDEV_AUX_CHILDREN_OFFLINE = ...
    VDEV_AUX_CORRUPT_DATA = ...
    VDEV_AUX_ERR_EXCEEDED = ...
    VDEV_AUX_EXTERNAL = ...
    VDEV_AUX_EXTERNAL_PERSIST = ...
    VDEV_AUX_IO_FAILURE = ...
    VDEV_AUX_NONE = ...
    VDEV_AUX_NO_REPLICAS = ...
    VDEV_AUX_OPEN_FAILED = ...
    VDEV_AUX_SPARED = ...
    VDEV_AUX_SPLIT_POOL = ...
    VDEV_AUX_TOO_SMALL = ...
    VDEV_AUX_UNSUP_FEAT = ...
    VDEV_AUX_VERSION_NEWER = ...
    VDEV_AUX_VERSION_OLDER = ...
    def __format__(self, format_spec: str, /) -> str: ...

class VDevState(enum.IntEnum):
    CANT_OPEN = ...
    CLOSED = ...
    DEGRADED = ...
    FAULTED = ...
    OFFLINE = ...
    ONLINE = ...
    REMOVED = ...
    UNKNOWN = ...
    def __format__(self, format_spec: str, /) -> str: ...

class VDevType(enum.StrEnum):
    """Vdev type for use with create_vdev_spec()."""
    DISK = ...
    FILE = ...
    MIRROR = ...
    RAIDZ1 = ...
    RAIDZ2 = ...
    RAIDZ3 = ...
    DRAID1 = ...
    DRAID2 = ...
    DRAID3 = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZFSDOSFlag(enum.IntFlag):
    ZFS_APPENDONLY = ...
    ZFS_ARCHIVE = ...
    ZFS_HIDDEN = ...
    ZFS_IMMUTABLE = ...
    ZFS_NODUMP = ...
    ZFS_NOUNLINK = ...
    ZFS_READONLY = ...
    ZFS_SPARSE = ...
    ZFS_SYSTEM = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZFSError(enum.IntEnum):
    EZFS_ACTIVE_POOL = ...
    EZFS_ACTIVE_SPARE = ...
    EZFS_ASHIFT_MISMATCH = ...
    EZFS_BADBACKUP = ...
    EZFS_BADCACHE = ...
    EZFS_BADDEV = ...
    EZFS_BADPATH = ...
    EZFS_BADPERM = ...
    EZFS_BADPERMSET = ...
    EZFS_BADPROP = ...
    EZFS_BADRESTORE = ...
    EZFS_BADSTREAM = ...
    EZFS_BADTARGET = ...
    EZFS_BADTYPE = ...
    EZFS_BADVERSION = ...
    EZFS_BADWHO = ...
    EZFS_BUSY = ...
    EZFS_CHECKPOINT_EXISTS = ...
    EZFS_CKSUM = ...
    EZFS_CROSSTARGET = ...
    EZFS_CRYPTOFAILED = ...
    EZFS_DEVOVERFLOW = ...
    EZFS_DEVRM_IN_PROGRESS = ...
    EZFS_DIFF = ...
    EZFS_DIFFDATA = ...
    EZFS_DISCARDING_CHECKPOINT = ...
    EZFS_DSREADONLY = ...
    EZFS_ERRORSCRUBBING = ...
    EZFS_ERRORSCRUB_PAUSED = ...
    EZFS_EXISTS = ...
    EZFS_EXPORT_IN_PROGRESS = ...
    EZFS_FAULT = ...
    EZFS_INITIALIZING = ...
    EZFS_INTR = ...
    EZFS_INVALCONFIG = ...
    EZFS_INVALIDNAME = ...
    EZFS_IO = ...
    EZFS_IOC_NOTSUPPORTED = ...
    EZFS_ISL2CACHE = ...
    EZFS_ISSPARE = ...
    EZFS_LABELFAILED = ...
    EZFS_MOUNTFAILED = ...
    EZFS_NAMETOOLONG = ...
    EZFS_NOCAP = ...
    EZFS_NODELEGATION = ...
    EZFS_NODEVICE = ...
    EZFS_NOENT = ...
    EZFS_NOHISTORY = ...
    EZFS_NOMEM = ...
    EZFS_NOREPLICAS = ...
    EZFS_NOSPC = ...
    EZFS_NOTSUP = ...
    EZFS_NOT_USER_NAMESPACE = ...
    EZFS_NO_CHECKPOINT = ...
    EZFS_NO_INITIALIZE = ...
    EZFS_NO_PENDING = ...
    EZFS_NO_RESILVER_DEFER = ...
    EZFS_NO_SCRUB = ...
    EZFS_NO_TRIM = ...
    EZFS_OPENFAILED = ...
    EZFS_PERM = ...
    EZFS_PIPEFAILED = ...
    EZFS_POOLPROPS = ...
    EZFS_POOLREADONLY = ...
    EZFS_POOLUNAVAIL = ...
    EZFS_POOL_INVALARG = ...
    EZFS_POOL_NOTSUP = ...
    EZFS_POSTSPLIT_ONLINE = ...
    EZFS_PROPNONINHERIT = ...
    EZFS_PROPREADONLY = ...
    EZFS_PROPSPACE = ...
    EZFS_PROPTYPE = ...
    EZFS_RAIDZ_EXPAND_IN_PROGRESS = ...
    EZFS_REBUILDING = ...
    EZFS_RECURSIVE = ...
    EZFS_REFTAG_HOLD = ...
    EZFS_REFTAG_RELE = ...
    EZFS_RESILVERING = ...
    EZFS_RESUME_EXISTS = ...
    EZFS_SCRUBBING = ...
    EZFS_SCRUB_PAUSED = ...
    EZFS_SCRUB_PAUSED_TO_CANCEL = ...
    EZFS_SHAREFAILED = ...
    EZFS_SHARENFSFAILED = ...
    EZFS_SHARESMBFAILED = ...
    EZFS_SUCCESS = ...
    EZFS_TAGTOOLONG = ...
    EZFS_THREADCREATEFAILED = ...
    EZFS_TOOMANY = ...
    EZFS_TRIMMING = ...
    EZFS_TRIM_NOTSUP = ...
    EZFS_UMOUNTFAILED = ...
    EZFS_UNKNOWN = ...
    EZFS_UNPLAYED_LOGS = ...
    EZFS_UNSHARENFSFAILED = ...
    EZFS_UNSHARESMBFAILED = ...
    EZFS_VDEVNOTSUP = ...
    EZFS_VDEV_NOTSUP = ...
    EZFS_VDEV_TOO_BIG = ...
    EZFS_VOLTOOBIG = ...
    EZFS_WRONG_PARENT = ...
    EZFS_ZONED = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZFSProperty(enum.IntEnum):
    ACLINHERIT = ...
    ACLMODE = ...
    ACLTYPE = ...
    ATIME = ...
    AVAILABLE = ...
    CANMOUNT = ...
    CASESENSITIVITY = ...
    CHECKSUM = ...
    CLONES = ...
    COMPRESSION = ...
    COMPRESSRATIO = ...
    CONTEXT = ...
    COPIES = ...
    CREATETXG = ...
    CREATION = ...
    DEDUP = ...
    DEFAULTGROUPOBJQUOTA = ...
    DEFAULTGROUPQUOTA = ...
    DEFAULTPROJECTOBJQUOTA = ...
    DEFAULTPROJECTQUOTA = ...
    DEFAULTUSEROBJQUOTA = ...
    DEFAULTUSERQUOTA = ...
    DEFCONTEXT = ...
    DEFER_DESTROY = ...
    DEVICES = ...
    DIRECT = ...
    DNODESIZE = ...
    ENCRYPTION = ...
    ENCRYPTIONROOT = ...
    EXEC = ...
    FILESYSTEM_COUNT = ...
    FILESYSTEM_LIMIT = ...
    FSCONTEXT = ...
    GUID = ...
    KEYFORMAT = ...
    KEYLOCATION = ...
    KEYSTATUS = ...
    LOGBIAS = ...
    LOGICALREFERENCED = ...
    LOGICALUSED = ...
    LONGNAME = ...
    MLSLABEL = ...
    MOUNTED = ...
    MOUNTPOINT = ...
    NBMAND = ...
    NORMALIZATION = ...
    OBJSETID = ...
    ORIGIN = ...
    OVERLAY = ...
    PBKDF2ITERS = ...
    PREFETCH = ...
    PRIMARYCACHE = ...
    QUOTA = ...
    READONLY = ...
    RECEIVE_RESUME_TOKEN = ...
    RECORDSIZE = ...
    REDACT_SNAPS = ...
    REDUNDANT_METADATA = ...
    REFCOMPRESSRATIO = ...
    REFERENCED = ...
    REFQUOTA = ...
    REFRESERVATION = ...
    RELATIME = ...
    RESERVATION = ...
    ROOTCONTEXT = ...
    SECONDARYCACHE = ...
    SETUID = ...
    SHARENFS = ...
    SHARESMB = ...
    SNAPDEV = ...
    SNAPDIR = ...
    SNAPSHOTS_CHANGED = ...
    SNAPSHOT_COUNT = ...
    SNAPSHOT_LIMIT = ...
    SPECIAL_SMALL_BLOCKS = ...
    SYNC = ...
    TYPE = ...
    USED = ...
    USEDBYCHILDREN = ...
    USEDBYDATASET = ...
    USEDBYREFRESERVATION = ...
    USEDBYSNAPSHOTS = ...
    USERREFS = ...
    UTF8ONLY = ...
    VERSION = ...
    VOLBLOCKSIZE = ...
    VOLMODE = ...
    VOLSIZE = ...
    VOLTHREADING = ...
    VSCAN = ...
    WRITTEN = ...
    XATTR = ...
    ZONED = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZFSType(enum.IntEnum):
    ZFS_TYPE_BOOKMARK = ...
    ZFS_TYPE_FILESYSTEM = ...
    ZFS_TYPE_INVALID = ...
    ZFS_TYPE_POOL = ...
    ZFS_TYPE_SNAPSHOT = ...
    ZFS_TYPE_VDEV = ...
    ZFS_TYPE_VOLUME = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZFSUserQuota(enum.IntEnum):
    GROUPOBJ_QUOTA = ...
    GROUPOBJ_USED = ...
    GROUP_QUOTA = ...
    GROUP_USED = ...
    PROJECTOBJ_QUOTA = ...
    PROJECTOBJ_USED = ...
    PROJECT_QUOTA = ...
    PROJECT_USED = ...
    USEROBJ_QUOTA = ...
    USEROBJ_USED = ...
    USER_QUOTA = ...
    USER_USED = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZPOOLProperty(enum.IntEnum):
    ALLOCATED = ...
    ALTROOT = ...
    ASHIFT = ...
    AUTOEXPAND = ...
    AUTOREPLACE = ...
    AUTOTRIM = ...
    AVAILABLE = ...
    BCLONERATIO = ...
    BCLONESAVED = ...
    BCLONEUSED = ...
    BOOTFS = ...
    CACHEFILE = ...
    CAPACITY = ...
    CHECKPOINT = ...
    COMMENT = ...
    COMPATIBILITY = ...
    DEDUPCACHED = ...
    DEDUPDITTO = ...
    DEDUPRATIO = ...
    DEDUP_TABLE_QUOTA = ...
    DEDUP_TABLE_SIZE = ...
    DEDUPSAVED = ...
    DEDUPUSED = ...
    CLASS_DEDUP_ALLOCATED = ...
    CLASS_DEDUP_AVAILABLE = ...
    CLASS_DEDUP_CAPACITY = ...
    CLASS_DEDUP_EXPANDSIZE = ...
    CLASS_DEDUP_FRAGMENTATION = ...
    CLASS_DEDUP_FREE = ...
    CLASS_DEDUP_SIZE = ...
    CLASS_DEDUP_USABLE = ...
    CLASS_DEDUP_USED = ...
    CLASS_ELOG_ALLOCATED = ...
    CLASS_ELOG_AVAILABLE = ...
    CLASS_ELOG_CAPACITY = ...
    CLASS_ELOG_EXPANDSIZE = ...
    CLASS_ELOG_FRAGMENTATION = ...
    CLASS_ELOG_FREE = ...
    CLASS_ELOG_SIZE = ...
    CLASS_ELOG_USABLE = ...
    CLASS_ELOG_USED = ...
    CLASS_LOG_ALLOCATED = ...
    CLASS_LOG_AVAILABLE = ...
    CLASS_LOG_CAPACITY = ...
    CLASS_LOG_EXPANDSIZE = ...
    CLASS_LOG_FRAGMENTATION = ...
    CLASS_LOG_FREE = ...
    CLASS_LOG_SIZE = ...
    CLASS_LOG_USABLE = ...
    CLASS_LOG_USED = ...
    CLASS_NORMAL_ALLOCATED = ...
    CLASS_NORMAL_AVAILABLE = ...
    CLASS_NORMAL_CAPACITY = ...
    CLASS_NORMAL_EXPANDSIZE = ...
    CLASS_NORMAL_FRAGMENTATION = ...
    CLASS_NORMAL_FREE = ...
    CLASS_NORMAL_SIZE = ...
    CLASS_NORMAL_USABLE = ...
    CLASS_NORMAL_USED = ...
    CLASS_SPECIAL_ALLOCATED = ...
    CLASS_SPECIAL_AVAILABLE = ...
    CLASS_SPECIAL_CAPACITY = ...
    CLASS_SPECIAL_ELOG_ALLOCATED = ...
    CLASS_SPECIAL_ELOG_AVAILABLE = ...
    CLASS_SPECIAL_ELOG_CAPACITY = ...
    CLASS_SPECIAL_ELOG_EXPANDSIZE = ...
    CLASS_SPECIAL_ELOG_FRAGMENTATION = ...
    CLASS_SPECIAL_ELOG_FREE = ...
    CLASS_SPECIAL_ELOG_SIZE = ...
    CLASS_SPECIAL_ELOG_USABLE = ...
    CLASS_SPECIAL_ELOG_USED = ...
    CLASS_SPECIAL_EXPANDSIZE = ...
    CLASS_SPECIAL_FRAGMENTATION = ...
    CLASS_SPECIAL_FREE = ...
    CLASS_SPECIAL_SIZE = ...
    CLASS_SPECIAL_USABLE = ...
    CLASS_SPECIAL_USED = ...
    DELEGATION = ...
    EXPANDSIZE = ...
    FAILMODE = ...
    FRAGMENTATION = ...
    FREE = ...
    FREEING = ...
    GUID = ...
    HEALTH = ...
    INVAL = ...
    LAST_SCRUBBED_TXG = ...
    LEAKED = ...
    LISTSNAPSHOTS = ...
    LOAD_GUID = ...
    MAXBLOCKSIZE = ...
    MAXDNODESIZE = ...
    MULTIHOST = ...
    NAME = ...
    READONLY = ...
    SIZE = ...
    TNAME = ...
    USABLE = ...
    USED = ...
    VERSION = ...
    def __format__(self, format_spec: str, /) -> str: ...

class ZPOOLStatus(enum.IntEnum):
    ZPOOL_STATUS_BAD_GUID_SUM = ...
    ZPOOL_STATUS_BAD_LOG = ...
    ZPOOL_STATUS_COMPATIBILITY_ERR = ...
    ZPOOL_STATUS_CORRUPT_CACHE = ...
    ZPOOL_STATUS_CORRUPT_DATA = ...
    ZPOOL_STATUS_CORRUPT_LABEL_NR = ...
    ZPOOL_STATUS_CORRUPT_LABEL_R = ...
    ZPOOL_STATUS_CORRUPT_POOL = ...
    ZPOOL_STATUS_ERRATA = ...
    ZPOOL_STATUS_FAILING_DEV = ...
    ZPOOL_STATUS_FAULTED_DEV_NR = ...
    ZPOOL_STATUS_FAULTED_DEV_R = ...
    ZPOOL_STATUS_FEAT_DISABLED = ...
    ZPOOL_STATUS_HOSTID_ACTIVE = ...
    ZPOOL_STATUS_HOSTID_MISMATCH = ...
    ZPOOL_STATUS_HOSTID_REQUIRED = ...
    ZPOOL_STATUS_INCOMPATIBLE_FEAT = ...
    ZPOOL_STATUS_IO_FAILURE_CONTINUE = ...
    ZPOOL_STATUS_IO_FAILURE_MMP = ...
    ZPOOL_STATUS_IO_FAILURE_WAIT = ...
    ZPOOL_STATUS_MISSING_DEV_NR = ...
    ZPOOL_STATUS_MISSING_DEV_R = ...
    ZPOOL_STATUS_NON_NATIVE_ASHIFT = ...
    ZPOOL_STATUS_OFFLINE_DEV = ...
    ZPOOL_STATUS_OK = ...
    ZPOOL_STATUS_REBUILDING = ...
    ZPOOL_STATUS_REBUILD_SCRUB = ...
    ZPOOL_STATUS_REMOVED_DEV = ...
    ZPOOL_STATUS_RESILVERING = ...
    ZPOOL_STATUS_UNSUP_FEAT_READ = ...
    ZPOOL_STATUS_UNSUP_FEAT_WRITE = ...
    ZPOOL_STATUS_VERSION_NEWER = ...
    ZPOOL_STATUS_VERSION_OLDER = ...
    def __format__(self, format_spec: str, /) -> str: ...


# ---------------------------------------------------------------------------
# Struct sequence types
# ---------------------------------------------------------------------------

class struct_vdev_create_spec:
    """Vdev creation specification for use with ZFS.create_pool()."""
    name: str | None
    vdev_type: VDevType | str
    children: tuple[struct_vdev_create_spec, ...] | None

class struct_vdev_stats:
    timestamp: int
    allocated: int
    space: int
    dspace: int
    pspace: int
    rsize: int
    esize: int
    read_errors: int
    write_errors: int
    checksum_errors: int
    initialize_errors: int
    dio_verify_errors: int
    slow_ios: int | None
    self_healed_bytes: int
    fragmentation: int | None
    scan_processed: int
    scan_removing: int
    rebuild_processed: int
    noalloc: int | None
    ops_read: int
    ops_write: int
    bytes_read: int
    bytes_write: int
    configured_ashift: int | None
    logical_ashift: int | None
    physical_ashift: int | None

class struct_vdev:
    name: str
    vdev_type: str
    guid: int
    state: VDevState
    stats: struct_vdev_stats | None
    children: tuple[struct_vdev, ...] | None
    top_guid: int | None

class struct_support_vdev:
    cache: tuple[struct_vdev, ...]
    log: tuple[struct_vdev, ...]
    special: tuple[struct_vdev, ...]
    dedup: tuple[struct_vdev, ...]

class struct_zpool_feature:
    guid: str
    description: str
    state: Literal["DISABLED", "ENABLED", "ACTIVE"]

class struct_zpool_scrub:
    func: ScanFunction
    state: ScanState
    start_time: int
    end_time: int
    to_examine: int
    examined: int
    skipped: int
    processed: int
    issued: int
    errors: int
    pass_exam: int
    pass_start: int
    pass_scrub_pause: int
    pass_scrub_spent_paused: int
    pass_issued: int
    error_scrub_func: ScanFunction | None
    error_scrub_state: ScanState | None
    error_scrub_start: int | None
    error_scrub_end: int | None
    error_scrub_examined: int | None
    error_scrub_to_be_examined: int | None
    pass_error_scrub_pause: int | None
    percentage: float | None

class struct_zpool_expand:
    state: ScanState
    expanding_vdev: int
    start_time: int
    end_time: int
    to_reflow: int
    reflowed: int
    waiting_for_resilver: int

class struct_zpool_status:
    status: ZPOOLStatus
    reason: str | None
    action: str | None
    message: str | None
    corrupted_files: tuple[str, ...]
    storage_vdevs: tuple[struct_vdev, ...]
    support_vdevs: struct_support_vdev
    spares: tuple[struct_vdev, ...]
    name: str
    guid: int

class struct_zfs_property_source:
    """Source information for a ZFS or pool property."""
    type: PropertySource
    value: str | None

class struct_zfs_property_data:
    """Individual property value and source information."""
    value: int | str | None
    raw: str
    source: struct_zfs_property_source | None

class struct_zpool_property_data:
    """Per-property data returned by ZFSPool.get_properties()."""
    prop: ZPOOLProperty
    value: int | str | None
    raw: str
    source: PropertySource | None

class struct_zpool_property:
    """Pool property bundle returned by ZFSPool.get_properties().

    Each attribute corresponds to a ZPOOLProperty member.
    Requested properties contain the parsed value directly (int for numeric
    properties, str for string/index properties); unrequested properties
    are None.

    Attribute names are the lowercase libzfs property names as returned by
    zpool_prop_to_name() (e.g. ``failmode``, ``listsnapshots``,
    ``expandsize``).  These differ from the ZPOOLProperty enum member names.
    """
    name:                         struct_zpool_property_data | None
    size:                         struct_zpool_property_data | None
    capacity:                     struct_zpool_property_data | None
    altroot:                      struct_zpool_property_data | None
    health:                       struct_zpool_property_data | None
    guid:                         struct_zpool_property_data | None
    version:                      struct_zpool_property_data | None
    bootfs:                       struct_zpool_property_data | None
    delegation:                   struct_zpool_property_data | None
    autoreplace:                  struct_zpool_property_data | None
    cachefile:                    struct_zpool_property_data | None
    failmode:                     struct_zpool_property_data | None
    listsnapshots:                struct_zpool_property_data | None
    autoexpand:                   struct_zpool_property_data | None
    dedupditto:                   struct_zpool_property_data | None
    dedupratio:                   struct_zpool_property_data | None
    free:                         struct_zpool_property_data | None
    allocated:                    struct_zpool_property_data | None
    readonly:                     struct_zpool_property_data | None
    ashift:                       struct_zpool_property_data | None
    comment:                      struct_zpool_property_data | None
    expandsize:                   struct_zpool_property_data | None
    freeing:                      struct_zpool_property_data | None
    fragmentation:                struct_zpool_property_data | None
    leaked:                       struct_zpool_property_data | None
    maxblocksize:                 struct_zpool_property_data | None
    tname:                        struct_zpool_property_data | None
    maxdnodesize:                 struct_zpool_property_data | None
    multihost:                    struct_zpool_property_data | None
    checkpoint:                   struct_zpool_property_data | None
    load_guid:                    struct_zpool_property_data | None
    autotrim:                     struct_zpool_property_data | None
    compatibility:                struct_zpool_property_data | None
    bcloneused:                   struct_zpool_property_data | None
    bclonesaved:                  struct_zpool_property_data | None
    bcloneratio:                  struct_zpool_property_data | None
    dedup_table_size:             struct_zpool_property_data | None
    dedup_table_quota:            struct_zpool_property_data | None
    dedupcached:                  struct_zpool_property_data | None
    last_scrubbed_txg:            struct_zpool_property_data | None
    dedupused:                    struct_zpool_property_data | None
    dedupsaved:                   struct_zpool_property_data | None
    available:                    struct_zpool_property_data | None
    usable:                       struct_zpool_property_data | None
    used:                         struct_zpool_property_data | None
    class_normal_size:            struct_zpool_property_data | None
    class_normal_capacity:        struct_zpool_property_data | None
    class_normal_free:            struct_zpool_property_data | None
    class_normal_allocated:       struct_zpool_property_data | None
    class_normal_available:       struct_zpool_property_data | None
    class_normal_usable:          struct_zpool_property_data | None
    class_normal_used:            struct_zpool_property_data | None
    class_normal_expandsize:      struct_zpool_property_data | None
    class_normal_fragmentation:   struct_zpool_property_data | None
    class_special_size:           struct_zpool_property_data | None
    class_special_capacity:       struct_zpool_property_data | None
    class_special_free:           struct_zpool_property_data | None
    class_special_allocated:      struct_zpool_property_data | None
    class_special_available:      struct_zpool_property_data | None
    class_special_usable:         struct_zpool_property_data | None
    class_special_used:           struct_zpool_property_data | None
    class_special_expandsize:     struct_zpool_property_data | None
    class_special_fragmentation:  struct_zpool_property_data | None
    class_dedup_size:             struct_zpool_property_data | None
    class_dedup_capacity:         struct_zpool_property_data | None
    class_dedup_free:             struct_zpool_property_data | None
    class_dedup_allocated:        struct_zpool_property_data | None
    class_dedup_available:        struct_zpool_property_data | None
    class_dedup_usable:           struct_zpool_property_data | None
    class_dedup_used:             struct_zpool_property_data | None
    class_dedup_expandsize:       struct_zpool_property_data | None
    class_dedup_fragmentation:    struct_zpool_property_data | None
    class_log_size:               struct_zpool_property_data | None
    class_log_capacity:           struct_zpool_property_data | None
    class_log_free:               struct_zpool_property_data | None
    class_log_allocated:          struct_zpool_property_data | None
    class_log_available:          struct_zpool_property_data | None
    class_log_usable:             struct_zpool_property_data | None
    class_log_used:               struct_zpool_property_data | None
    class_log_expandsize:         struct_zpool_property_data | None
    class_log_fragmentation:      struct_zpool_property_data | None
    class_elog_size:              struct_zpool_property_data | None
    class_elog_capacity:          struct_zpool_property_data | None
    class_elog_free:              struct_zpool_property_data | None
    class_elog_allocated:         struct_zpool_property_data | None
    class_elog_available:         struct_zpool_property_data | None
    class_elog_usable:            struct_zpool_property_data | None
    class_elog_used:              struct_zpool_property_data | None
    class_elog_expandsize:        struct_zpool_property_data | None
    class_elog_fragmentation:     struct_zpool_property_data | None
    class_special_elog_size:          struct_zpool_property_data | None
    class_special_elog_capacity:      struct_zpool_property_data | None
    class_special_elog_free:          struct_zpool_property_data | None
    class_special_elog_allocated:     struct_zpool_property_data | None
    class_special_elog_available:     struct_zpool_property_data | None
    class_special_elog_usable:        struct_zpool_property_data | None
    class_special_elog_used:          struct_zpool_property_data | None
    class_special_elog_expandsize:    struct_zpool_property_data | None
    class_special_elog_fragmentation: struct_zpool_property_data | None

class struct_zfs_crypto_info:
    """Encryption status information for a ZFS dataset or volume."""
    is_root: bool
    """Whether this dataset is an encryption root."""
    encryption_root: str | None
    """Name of the encryption root dataset, or None if not encrypted."""
    key_location: str
    """The keylocation property value (e.g. 'prompt', 'file://...')."""
    key_is_loaded: bool
    """Whether the wrapping key is currently loaded."""


# ---------------------------------------------------------------------------
# C extension types (not directly instantiable; use factories)
# ---------------------------------------------------------------------------

class ZFSCrypto:
    """Encryption operations for a ZFS dataset or volume."""

    def info(self) -> struct_zfs_crypto_info: ...

    def load_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> None: ...

    def unload_key(self) -> None: ...

    def check_key(
        self,
        *,
        key: str | bytes | None = None,
        key_location: str | None = None,
    ) -> bool: ...

    def change_key(self, *, info: Any) -> None: ...

    def inherit_key(self) -> None: ...


class ZFSSnapshot:
    def get_holds(self) -> tuple[str, ...]: ...
    def get_clones(self) -> tuple[str, ...]: ...
    def clone(self, *, name: str, properties: dict[str, Any] | None = None) -> None: ...


class ZFSPool:
    """Represents a ZFS pool."""
    @property
    def name(self) -> str: ...

    def prefetch(self) -> None: ...

    def status(
        self,
        *,
        asdict: bool = ...,
        get_stats: bool = ...,
        follow_links: bool = ...,
        full_path: bool = ...,
    ) -> struct_zpool_status | dict[str, Any]: ...

    def get_features(self, *, asdict: bool = ...) -> dict[str, struct_zpool_feature] | dict[str, dict[str, str]]: ...

    def scrub_info(self) -> struct_zpool_scrub | None: ...

    def expand_info(self) -> struct_zpool_expand | None: ...

    def scan(self, *, func: ScanFunction, cmd: ScanScrubCmd = ...) -> None: ...

    def get_properties(self, *, properties: set[ZPOOLProperty]) -> struct_zpool_property: ...

    def set_properties(self, *, properties: dict[str, Any]) -> None: ...

    def get_user_properties(self) -> dict[str, str]: ...

    def set_user_properties(self, *, user_properties: dict[str, str]) -> None: ...

    def offline_device(self, *, device: str, temporary: bool = False) -> None: ...

    def online_device(self, *, device: str, expand: bool = False) -> None: ...

    def add_vdevs(
        self,
        *,
        storage_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        cache_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        log_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        special_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        dedup_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        spare_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        force: bool = False,
    ) -> None: ...

    def attach_vdev(
        self,
        *,
        device: str,
        new_device: struct_vdev_create_spec,
        rebuild: bool = False,
        force: bool = False,
    ) -> None: ...

    def replace_vdev(
        self,
        *,
        device: str,
        new_device: struct_vdev_create_spec | None = None,
        rebuild: bool = False,
    ) -> None: ...

    def detach_vdev(self, *, device: str) -> None: ...

    def remove_vdev(self, *, device: str) -> None: ...

    def cancel_remove_vdev(self) -> None: ...

    def iter_history(
        self,
        *,
        skip_internal: bool = True,
        since: int = 0,
        until: int = 0,
    ) -> Iterator[dict[str, Any]]: ...


class ZFS:
    """ZFS library handle. Obtain via truenas_pylibzfs.open_handle()."""
    def open_pool(self, *, name: str) -> ZFSPool: ...
    def open_resource(self, **kwargs: Any) -> Any: ...
    def create_resource(self, *, name: str, type: ZFSType, properties: dict[str, Any] | None = None, crypto: Any | None = None) -> None: ...
    def create_pool(
        self,
        *,
        name: str,
        storage_vdevs: Iterable[struct_vdev_create_spec],
        cache_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        log_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        special_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        dedup_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        spare_vdevs: Iterable[struct_vdev_create_spec] | None = None,
        properties: dict[ZPOOLProperty, str] | None = None,
        filesystem_properties: dict[ZFSProperty, str] | None = None,
        force: bool = False,
    ) -> None: ...
    def destroy_pool(self, *, name: str, force: bool = False) -> None: ...
    def export_pool(self, *, name: str, force: bool = False) -> None: ...
    def destroy_resource(self, *, name: str) -> bool: ...
    def iter_pools(self, *, callback: Any, state: Any) -> bool: ...
    def iter_root_filesystems(self, *, callback: Any, state: Any) -> bool: ...
    def resource_cryptography_config(self, *, keyformat: str | None = None, keylocation: str | None = None, pbkdf2iters: int | None = None, key: str | bytes | None = None) -> Any: ...
    def zpool_events(self, *, blocking: bool = False, skip_existing_events: bool = True) -> Iterator[dict[str, Any]]: ...
    def import_pool_find(self, *, cache_file: str | None = None, device: str | None = None) -> list[struct_zpool_status]: ...
    def import_pool(self, *, name: str | None = None, guid: int | None = None,
                    allow_missing_log: bool = False, altroot: str | None = None,
                    force: bool = False, properties: dict[ZPOOLProperty | str, str] | None = None,
                    temporary_name: str | None = None, device: str | None = None) -> ZFSPool: ...
