from typing import Any
from .libzfs_types import ZPOOLProperty, ZPOOLStatus

ZFS_FILESYSTEM_PROPERTIES: Any
ZFS_FILESYSTEM_READONLY_PROPERTIES: Any
ZFS_FILESYSTEM_SNAPSHOT_PROPERTIES: Any
ZFS_FILESYSTEM_SNAPSHOT_READONLY_PROPERTIES: Any
ZFS_SPACE_PROPERTIES: Any
ZFS_VOLUME_PROPERTIES: Any
ZFS_VOLUME_READONLY_PROPERTIES: Any
ZFS_VOLUME_SNAPSHOT_PROPERTIES: Any
ZFS_VOLUME_SNAPSHOT_READONLY_PROPERTIES: Any
ZPOOL_STATUS_NONRECOVERABLE: frozenset[ZPOOLStatus]
ZPOOL_STATUS_RECOVERABLE: frozenset[ZPOOLStatus]
ZPOOL_READONLY_PROPERTIES: frozenset[ZPOOLProperty]
ZPOOL_PROPERTIES: frozenset[ZPOOLProperty]
ZPOOL_CLASS_SPACE: frozenset[ZPOOLProperty]
ZPOOL_SPACE: frozenset[ZPOOLProperty]
